affinity_weight: 0.01
all_atoms: false
atom_max_neighbors: 8
atom_radius: 5
batch_size: 40
c_alpha_max_neighbors: 24
cache_path: data/cache
config: null
cross_distance_embed_dim: 32
cross_max_distance: 80
cudnn_benchmark: true
data_dir: data/PDBBind_af2_aligned/
distance_embed_dim: 32
dropout: 0.1
dynamic_max_cross: true
ema_rate: 0.999
embedding_scale: 1000
embedding_type: sinusoidal
esm_embeddings_path: data/esm2_3billion_embeddings.pt
finetune_freq: null
inference_earlystop_goal: max
inference_earlystop_metric: valinf_rmsds_lt2
inference_steps: 20
info_path: data/PDBBind_af2_aligned.csv
lddt_weight: 0.99
limit_complexes: 0
log_dir: workdir
lr: 0.001
matching_maxiter: 20
matching_popsize: 20
max_lig_size: null
max_radius: 5.0
n_epochs: 800
no_batch_norm: false
no_torsion: false
ns: 72
num_conformers: 1
num_conv_layers: 6
num_dataloader_workers: 1
num_finetune_complexes: 500
num_inference_complexes: 500
num_workers: 1
nv: 12
only_test: false
pin_memory: true
project: difdock_train
receptor_radius: 15.0
remove_hs: true
res_chi_sigma_max: 1
res_chi_sigma_min: 0.01
res_chi_weight: 0.33
res_rot_sigma_max: 1
res_rot_sigma_min: 0.01
res_rot_weight: 0.33
res_tr_sigma_max: 1
res_tr_sigma_min: 0.01
res_tr_weight: 0.33
restart_dir: null
restart_lr: null
rot_sigma_max: 1.55
rot_sigma_min: 0.03
rot_weight: 0.33
run_name: big_score_model_sanyueqi_with_time
sample_batch_size: 16
scale_by_sigma: true
scheduler: plateau
scheduler_patience: 30
sigma_embed_dim: 32
split_test: data/splits/timesplit_test
split_train: data/splits/timesplit_no_lig_overlap_train
split_val: data/splits/timesplit_test
test_sigma_intervals: true
tor_sigma_max: 3.14
tor_sigma_min: 0.0314
tor_weight: 0.33
tr_sigma_max: 19.0
tr_sigma_min: 0.1
tr_weight: 0.33
use_ema: true
use_second_order_repr: false
val_inference_freq: 5
w_decay: 0.0
wandb: false
